<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('jobs', ['as'=> 'jobs.index', 'uses' => 'JobController@index']);
Route::post('jobs', ['as'=> 'jobs.store', 'uses' => 'JobController@store']);
Route::get('jobs/create', ['as'=> 'jobs.create', 'uses' => 'JobController@create']);
Route::put('jobs/{jobs}', ['as'=> 'jobs.update', 'uses' => 'JobController@update']);
Route::patch('jobs/{jobs}', ['as'=> 'jobs.update', 'uses' => 'JobController@update']);
Route::get('jobs/{id}/delete', array('as' => 'jobs.delete', 'uses' => 'JobController@getDelete'));
Route::get('jobs/{id}/confirm-delete', array('as' => 'jobs.confirm-delete', 'uses' => 'JobController@getModalDelete'));
Route::get('jobs/{jobs}', ['as'=> 'jobs.show', 'uses' => 'JobController@show']);
Route::get('jobs/{jobs}/edit', ['as'=> 'jobs.edit', 'uses' => 'JobController@edit']);

});
